name: .NET Test Pipeline
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest  # ← DIT IS DE FIX!
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build --no-restore --configuration Release
        
      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
