name: .NET Tests

on:
  push:
    branches: [main, feature/*]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore CoreLibrary
        run: dotnet restore CoreLibrary/CoreLibrary.csproj

      - name: Restore TestCore
        run: dotnet restore TestCore/TestCore.csproj

      - name: Build CoreLibrary
        run: dotnet build CoreLibrary/CoreLibrary.csproj --no-restore

      - name: Build TestCore
        run: dotnet build TestCore/TestCore.csproj --no-restore

      - name: Run Tests
        run: dotnet test TestCore/TestCore.csproj --no-build
