name: MAUI Unit Tests

on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest   # MAUI werkt stabieler op Windows
    steps:
      # 1. Haal de repository op
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installeer .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Installeer MAUI workloads (optioneel, alleen nodig voor platform builds)
      - name: Install MAUI workloads
        run: dotnet workload install maui-android

      # 4. Restore dependencies van testproject
      - name: Restore dependencies
        run: dotnet restore TestCore/TestCore.csproj

      # 5. Build testproject in Debug (stabiel voor tests)
      - name: Build test project
        run: dotnet build TestCore/TestCore.csproj --configuration Debug

      # 6. Run unit tests
      - name: Run unit tests
        run: dotnet test TestCore/TestCore.csproj --configuration Debug --no-build --verbosity normal
